# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='token.proto',
  package='stance',
  serialized_pb=_b('\n\x0btoken.proto\x12\x06stance\"%\n\x05Token\x12\r\n\x05token\x18\x01 \x02(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\'\n\x06Tokens\x12\x1d\n\x06tokens\x18\x01 \x03(\x0b\x32\r.stance.Token')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='stance.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='stance.Token.token', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='stance.Token.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=60,
)


_TOKENS = _descriptor.Descriptor(
  name='Tokens',
  full_name='stance.Tokens',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tokens', full_name='stance.Tokens.tokens', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=101,
)

_TOKENS.fields_by_name['tokens'].message_type = _TOKEN
DESCRIPTOR.message_types_by_name['Token'] = _TOKEN
DESCRIPTOR.message_types_by_name['Tokens'] = _TOKENS

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), dict(
  DESCRIPTOR = _TOKEN,
  __module__ = 'token_pb2'
  # @@protoc_insertion_point(class_scope:stance.Token)
  ))
_sym_db.RegisterMessage(Token)

Tokens = _reflection.GeneratedProtocolMessageType('Tokens', (_message.Message,), dict(
  DESCRIPTOR = _TOKENS,
  __module__ = 'token_pb2'
  # @@protoc_insertion_point(class_scope:stance.Tokens)
  ))
_sym_db.RegisterMessage(Tokens)


# @@protoc_insertion_point(module_scope)
