# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tweet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tweet.proto',
  package='stance',
  serialized_pb=_b('\n\x0btweet.proto\x12\x06stance\"*\n\x05Tweet\x12\r\n\x05tweet\x18\x01 \x02(\t\x12\x12\n\x06tokens\x18\x02 \x03(\x05\x42\x02\x10\x01\"\'\n\x06Tweets\x12\x1d\n\x06tweets\x18\x01 \x03(\x0b\x32\r.stance.Tweet')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TWEET = _descriptor.Descriptor(
  name='Tweet',
  full_name='stance.Tweet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tweet', full_name='stance.Tweet.tweet', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tokens', full_name='stance.Tweet.tokens', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=65,
)


_TWEETS = _descriptor.Descriptor(
  name='Tweets',
  full_name='stance.Tweets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tweets', full_name='stance.Tweets.tweets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=106,
)

_TWEETS.fields_by_name['tweets'].message_type = _TWEET
DESCRIPTOR.message_types_by_name['Tweet'] = _TWEET
DESCRIPTOR.message_types_by_name['Tweets'] = _TWEETS

Tweet = _reflection.GeneratedProtocolMessageType('Tweet', (_message.Message,), dict(
  DESCRIPTOR = _TWEET,
  __module__ = 'tweet_pb2'
  # @@protoc_insertion_point(class_scope:stance.Tweet)
  ))
_sym_db.RegisterMessage(Tweet)

Tweets = _reflection.GeneratedProtocolMessageType('Tweets', (_message.Message,), dict(
  DESCRIPTOR = _TWEETS,
  __module__ = 'tweet_pb2'
  # @@protoc_insertion_point(class_scope:stance.Tweets)
  ))
_sym_db.RegisterMessage(Tweets)


_TWEET.fields_by_name['tokens'].has_options = True
_TWEET.fields_by_name['tokens']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
